Go_Final_Sprint
EnrikeM/Yandex_final_project_Go pull request #1
Opened 2024-08-26 20:05 UTC by EnrikeM

2024-08-27 16:30 UTC, dirtymew requested changes
Привет Энрике

отличная работа:
 - задания со звездочкой
 - документация и swagger
 - логи
 - структура и архитектура решения

есть что поправить - дал комментарии, для первой итерации думаю достаточно

2024-08-27 16:30 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.23
лучше ту же версию go что описана в go mod использовать go 1.22.0

2024-08-27 16:30 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /my_app ./app/cmd/main.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 это тоже все лучше в ENV

2024-08-27 16:30 UTC, dirtymew commented on Dockerfile
> +CMD ["/my_app"]
приложение стоит как-то посерьезнее назвать

2024-08-27 16:30 UTC, dirtymew commented on env
> +TODO_PORT=7540
файл лучше назвать .env

2024-08-27 16:30 UTC, dirtymew commented on app/cmd/main.go
> +	if err != nil {
`if err := run(); err != nil {` ...

2024-08-27 16:30 UTC, dirtymew commented on app/internal/calc/calc.go
> +		for {
тут кажется перемудрил с ветками и бесконечными циклами

бесконечные циклы старайся вообще не использовать.

я бы рекомендовал тебе это переделать

2024-08-27 16:30 UTC, dirtymew commented on app/internal/httpsrv/api.go
> +		r:      chi.NewRouter(),
плохое названия для поля - назови router

2024-08-27 16:30 UTC, dirtymew commented on app/internal/httpsrv/api.go
> +	a.Register(a.r)
а почему в конструкторе NewAPI сразу это не сделать?

2024-08-27 16:30 UTC, dirtymew commented on app/internal/httpsrv/api.go
> +		log.Fatal(fmt.Errorf("error starting server %w", err))
а зачем тут паниковать? лучше тут ошибку вернуть у тебя же main и так паникует

2024-08-27 16:30 UTC, dirtymew commented on app/internal/httpsrv/delete_task_handler.go
> +	if _, err := storage.GetTask(a.DB, taskID); err != nil {
лушнее - DeleteTask достаточно

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +package storage
utils/tools/helpers - считается плохой практикой - тут все можно в storage.go положить

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +func GetTask(db *sql.DB, taskID string) (Task, error) {
тут лучше сделать структуру - как с api - или подсмотри в задании про посылки

и все функции сделать методами

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +	query := "SELECT * FROM scheduler WHERE id = ?"
лучше явно поля указывать чем *

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +			query = "SELECT * FROM scheduler WHERE title LIKE ? OR comment LIKE ? ORDER BY date LIMIT 10"
лимит в константу вынести

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +			search = searchDate.Format("20060102")
20060102 - тоже в константу и везде использовать

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +	if err != nil {
тут можно проверить rowsAfffected и вернуть ошибку - так будет меньше на один запрос к бд - выше комменатий тоже оставил

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +func RedactTask(db *sql.DB, task Task) error {
Update

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +func GetLastId(task Task, db *sql.DB) (string, error) {
Add

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +	res := strconv.Itoa(int(resInt))
тут что-то переборшил с приведением типов

2024-08-27 16:30 UTC, dirtymew commented on app/internal/storage/utils.go
> +	res := strconv.Itoa(int(resInt))
FormatInt

2024-08-27 16:30 UTC, dirtymew commented on app/internal/httpsrv/utils.go
> +func validate(t *storage.Task) error {
кажется это может быть метод структуры Task

2024-08-27 16:30 UTC, dirtymew commented on app/internal/httpsrv/update_task_handler.go
> +	if _, err := storage.GetTask(a.DB, task.ID); err != nil {
уже писал про delete тут тоже самое

2024-08-27 16:30 UTC, dirtymew commented on app/internal/httpsrv/update_task_handler.go
> +	err = validate(&validateTask)
зачем перекладывал в еше одну структуру - почему task не использовать

2024-08-27 16:30 UTC, dirtymew commented on app/internal/httpsrv/post_task_handler.go
> +type Task struct {
хмм а зачем есть уже такая структура - одно я думаю достаточно

2024-08-28 16:18 UTC, dirtymew requested changes
Привет Энрике

дал комментарии что улучшить и поправить - в остальном можно считать все готово

2024-08-28 16:18 UTC, dirtymew commented on app/cmd/main.go
> +	dbParams := storage.New(nil, *config)
вот тут не понятно - ты инициализируешь storage

потом передаешь зависимостью его DB в api и там еще раз инициализируешь еще один storage

так не надо

тут инициализируй его одни раз и в api передай его и работай в api c этим экземпляром

2024-08-28 16:18 UTC, dirtymew commented on app/cmd/main.go
> +		if err := dbParams.DB.Close(); err != nil {
вообще не стоит подключение так выставлять - я бы не делал у storage DB экспорируемым полем

и в целом не очень логично получилось

проще сделать что-то  такое

```
dbConn := storage.GetDb(config)

storage := storage.New(dbConn)

api := httpsrv.NewAPI(storage, config)

```

2024-08-28 16:18 UTC, dirtymew commented on app/cmd/main.go
> +	config, err := config.New()
пусть тебе config.New() вернут нужнный тип чтобы не делать *config

2024-08-28 16:18 UTC, dirtymew commented on app/internal/httpsrv/api.go
> +	DB     storage.Scheduler
storage

2024-08-28 16:18 UTC, dirtymew commented on app/internal/storage/storage.go
> +		query = `SELECT id, date, title, comment, repeat FROM scheduler ORDER BY date DESC LIMIT :limit`
сортировать нужно в другом порядке - а то на фронте в верху самы дальние события

2024-08-28 16:18 UTC, dirtymew commented on app/internal/httpsrv/signin_handler.go
> +func (a *API) auth(next http.Handler) http.Handler {
кажется что авторизация не работает - @EnrikeM 

я проверял у меня фронт приложение не отображает форму ввода пароля а сразу показывает задачи

странно что тесты проходят - но мб там нет такого кейса

2024-08-28 16:18 UTC, dirtymew commented on app/internal/httpsrv/signin_handler.go
> +func (a *API) auth(next http.Handler) http.Handler {
это задание со * поэтому зачту и без него

но раз ты уже все сделал лучше чтобы все заработало как надо

2024-08-28 17:31 UTC, EnrikeM commented on app/internal/httpsrv/signin_handler.go
> +func (a *API) auth(next http.Handler) http.Handler {
Привет!
Да, действительно, был баг
Поправил, чтобы middleware работал и на ручку выдачи всех задач

2024-08-28 18:59 UTC, dirtymew approved these changes
Привет Энрике

задание считаю выполненным - авторизация так и не заработала, но там совсем меленькая помарка

указал где

2024-08-28 18:59 UTC, dirtymew commented on app/internal/apierrors/apierrors.go
> +	w.WriteHeader(http.StatusBadRequest)
авторизация не работает из-за еще одного бага

тут w.WriteHeader(statusCode)


вообще я бы этот пакет советовал переделать - назвать response и перенес бы функцию сюда WriteResponse

2024-08-28 19:09 UTC, EnrikeM commented on app/internal/apierrors/apierrors.go
> +	w.WriteHeader(http.StatusBadRequest)
Да, проглядел
Поправил

2024-12-31 14:03 UTC, merged